language: android
dist: trusty
before_install:
 - chmod +x gradlew
android:
  components:
    - tools
    - build-tools-30.0.3
    - android-30
  licenses:
    - '.+'
script:
  - ./gradlew build connectedCheck
